### PR TITLE
Fix deploy state detection

### LINKED ISSUE #20: Can't use an action byte in bridge deployment
When deploying the bridge, there is no bridge input, thus there is no dedicated witness for the bridge. Bridge deployment state transition should be detected by the virtue of there being no bridge script in the inputs.

### PR DESCRIPTION
**Pull request by TheReturnOfJan**
Resolves #20

### CODE REVIEW

File: packages/parent-bridge/contracts/parent-bridge/src/main.rs [hunk 1]
```diff
@@ -88,6 +88,36 @@ enum StateTransition {
 }
 
 impl StateTransition {
+    fn get() -> Result<Self, Error> {
```
Comment (johannbarbie) [inline packages/parent-bridge/contracts/parent-bridge/src/main.rs:91]: nice job grouping code into the type.

**Review by johannbarbie — APPROVED** [review]
the transaction is now alligned with the spec at https://github.com/leapdao/nervos/blob/master/docs/parentBridge.md
